#!/bin/bash

#SBATCH --job-name d2q9-bgk-parallel
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --cpus-per-task 28
#SBATCH --time 00:20:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --exclusive
#SBATCH --output d2q9-bgk-parallel-256.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
#./d2q9-bgk-parallel input_128x128.params obstacles_128x128.dat
#./d2q9-bgk-parallel input_128x256.params obstacles_128x256.dat
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
#./d2q9-bgk-parallel input_1024x1024.params obstacles_1024x1024.dat

OMP_NUM_THREADS=6
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 6

OMP_NUM_THREADS=7
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 7

OMP_NUM_THREADS=8
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 8

OMP_NUM_THREADS=9
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 9

OMP_NUM_THREADS=10
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 10

OMP_NUM_THREADS=11
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 11

OMP_NUM_THREADS=12
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 12

OMP_NUM_THREADS=13
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 13

OMP_NUM_THREADS=14
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 14

OMP_NUM_THREADS=15
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 15

OMP_NUM_THREADS=16
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 16

OMP_NUM_THREADS=17
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 17

OMP_NUM_THREADS=18
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 18

OMP_NUM_THREADS=19
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 19

OMP_NUM_THREADS=20
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 20

OMP_NUM_THREADS=21
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 21

OMP_NUM_THREADS=22
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 22

OMP_NUM_THREADS=23
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 23

OMP_NUM_THREADS=24
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 24

OMP_NUM_THREADS=25
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 25

OMP_NUM_THREADS=26
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 26

OMP_NUM_THREADS=27
./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
echo 27
