#!/bin/bash

#SBATCH --nodes 4
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --exclude compute[100,101,102,103,104]
#SBATCH --job-name d2q9-bgk
#SBATCH --time 00:40:00
#SBATCH --output d2q9-bgk-4.out
#SBATCH --exclusive
module load languages/intel/2020-u4

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
#srun --mpi=pmi2 -n 1 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun --mpi=pmi2 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# srun --mpi=pmi2 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# srun --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

srun --mpi=pmi2 -N 4 -n 85 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 86 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 87 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 88 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 89 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 90 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 91 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 92 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 93 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 94 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 95 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 96 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 97 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 98 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 99 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 100 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 101 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 102 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 103 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 104 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 105 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 106 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 107 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 108 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 109 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 110 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 111 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 4 -n 112 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat


