#!/bin/bash

#SBATCH --nodes 1
#SBATCH --ntasks-per-node 28
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --exclude compute[100,101,102,103,104]
#SBATCH --job-name d2q9-bgk
#SBATCH --time 01:00:00
#SBATCH --output d2q9-bgk-1.out
#SBATCH --exclusive
module load languages/intel/2020-u4

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
srun --mpi=pmi2 -N 1 -n 1 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
# srun --mpi=pmi2 -N 1 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# srun --mpi=pmi2 -N 1 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
# srun --mpi=pmi2 -N 1 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

srun --mpi=pmi2 -N 1 -n 2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 3 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 4 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 5 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 6 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 7 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 8 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 9 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 10 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 11 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 12 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 13 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 14 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 15 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 16 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 17 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 18 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 19 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 20 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 21 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 22 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 23 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 24 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 25 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 26 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 27 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
srun --mpi=pmi2 -N 1 -n 28 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat



