#!/bin/bash

#SBATCH --job-name d2q9-bgk-serial
#SBATCH --nodes 1
#SBATCH --ntasks-per-node 1
#SBATCH --cpus-per-task 28
#SBATCH --time 00:20:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk-serial-advise.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#advixe-gui ./d2q9-bgk-serial
advixe-cl --collect=survey  --project-dir=advisor-data  ./d2q9-bgk-serial
advixe-cl --collect=map --project-dir=advisor-data  ./d2q9-bgk-serial
advixe-cl --collect=dependencies --project-dir=advisor-data  ./d2q9-bgk-serial
advixe-cl --collect=tripcounts  --project-dir=advisor-data  ./d2q9-bgk-serial
#! Run the executable
#./d2q9-bgk-serial input_128x128.params obstacles_128x128.dat
#./d2q9-bgk-parallel input_128x256.params obstacles_128x256.dat
#./d2q9-bgk-parallel input_256x256.params obstacles_256x256.dat
#./d2q9-bgk-parallel input_1024x1024.params obstacles_1024x1024.dat